services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: ck_db
    volumes:
      - dbbase:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8000:80"
  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - "6379:6379"

volumes:
  dbbase: